name: Run Action from Another Repo

on:
  workflow_dispatch:

jobs:
  run_action:
    runs-on: ubuntu-latest  # 使用するOS
    steps:
      # 現在のリポジトリをチェックアウト
      - name: Checkout current repository
        uses: actions/checkout@v2

      # `actions/common/load-config/action.yaml` のアクションを実行
      - name: Run the action from actionDemo repo
        id: load-config
        uses: TingWangPass/actionDemo/.github/actions/common/load-config@main
        with:
          config_file: .github/actions/config/tst-config.yaml

      - name: Show Output1
        run: |
          echo "Outputs:"
          echo "JDK version: ${{ fromJson(steps.load-config.outputs.github_output).jdk }}"
          echo "slack_teamDomain: ${{ fromJson(steps.load-config.outputs.github_output).slack_teamDomain }}"
          echo "slack_webhookUrl: ${{ fromJson(steps.load-config.outputs.github_output).slack_webhookUrl }}"
          echo "parameter_store: ${{ fromJson(steps.load-config.outputs.github_output).parameter_store }}"

      # - name: Run the get-aws-ps-param from actionDemo repo
      #   id: get-aws-ps-param
      #   uses: TingWangPass/actionDemo/.github/actions/common/get-aws-ps-param@main
      #   with:
      #     input_json: ${{ toJson(fromJson(steps.load-config.outputs.github_output).parameter_store) }}

      # - name: Show Output2
      #   run: |
      #     echo "Outputs:"
      #     echo "user: ${{ fromJson(steps.get-aws-ps-param.outputs.github_output).user }}"
      #     echo "password: ${{ fromJson(steps.get-aws-ps-param.outputs.github_output).password }}"

      - name: Run frontend setup
        id: init-frontend
        uses: TingWangPass/actionDemo/.github/actions/common/init-frontend@main
        with:
          nodejs: ${{ fromJson(steps.load-config.outputs.github_output).nodejs }}
          pnpm: ${{ fromJson(steps.load-config.outputs.github_output).pnpm }}
          jdk: ${{ fromJson(steps.load-config.outputs.github_output).jdk }}
          gradle: ${{ fromJson(steps.load-config.outputs.github_output).gradle }}


